version: 2

sources:
- name: FCB
  database: "{{env_var('DBT_FCB_SOURCE_DATABASE')}}"
  schema: "{{var('source_sch_fcb')}}"
  tables:
    - name: ORDERS_RAW
    - name: RAW_ACCOUNTS
    - name: RAW_CUSTOMERS
    - name: RAW_TRANSACTIONS
