version: 2

sources:
- name: FCB
  database: "{{env_var('DBT_FCB_SOURCE_DATABASE')}}"
  schema: "{{var('source_sch_fcb')}}"
  tables:
    - name: ORDERS_RAW
    - name: RAW_ACCOUNTS
    - name: RAW_CUSTOMERS
    - name: RAW_TRANSACTIONS

- name: tpch_sample
  database: "{{env_var('DBT_SNOWFLAKE_DEMO_SOURCE')}}"
  schema: "{{ var('source_sch_demo')}}"
  tables:
      - name: LINEITEM
      - name: CUSTOMER
      - name: ORDERS
      - name: PARTSUPP
      - name: SUPPLIER
      - name: PART
      - name: NATION
      - name: REGION